# Generated by Django 2.0 on 2022-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='totalscore',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
