# Generated by Django 2.0 on 2022-01-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deptartment',
            new_name='department',
        ),
    ]
