# Generated by Django 2.0 on 2022-04-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earts', '0004_performance_totalscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='STUDENT',
        ),
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s1', to='earts.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2', to='earts.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3', to='earts.student'),
        ),
    ]
