# Generated by Django 2.0 on 2022-04-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earts', '0008_programs_program_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments_rating',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='JUDGES',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='STUDENT',
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
